type User @table {
  name: String!
  email: String!
  role: String!
}

type Course @table {
  title: String!
  description: String!
  instructor: User!
  syllabusUrl: String
  startDate: Date
}

type Enrollment @table {
  student: User!
  course: Course!
  enrollmentDate: Date!
}

type Assignment @table {
  title: String!
  dueDate: Timestamp!
  course: Course!
  description: String
  maxPoints: Int
}

type Submission @table {
  assignment: Assignment!
  student: User!
  submissionUrl: String!
  grade: Int
  instructorFeedback: String
}

type DiscussionPost @table {
  content: String!
  course: Course!
  user: User!
  timestamp: Timestamp
}